### ISSUE TITLE
Can not edit

### ISSUE THREAD

**Issue by Dong142857** [cyh-sj/FaceEdit3D#1]
Hi, I tried running the command `python gen_inversion_wraped_images.py --outdir=out --network=ffhqrebalanced512-128.pkl --edit_shape True --directions=./editing_direction/fat.npy`, but the synthesis result doesn’t seem to show any changes. Is there anything wrong with my configuration? Also, how can I edit my own face? Are there any interactive applications available, similar to the original DragGAN implementation (e.g., using Imgui or Gradio)?
![gihub_issue](https://github.com/user-attachments/assets/51810331-877c-4545-9ebd-deef817ac7e3)

**Comment by cyh-sj** [comment]
> 你好，我尝试运行命令`python gen_inversion_wraped_images.py --outdir=out --network=ffhqrebalanced512-128.pkl --edit_shape True --directions=./editing_direction/fat.npy`，但合成结果似乎没有显示任何变化。我的配置有什么问题吗？另外，我该如何编辑自己的脸？是否有任何可用的交互式应用程序，类似于原始的 DragGAN 实现（例如，使用 Imgui 或 Gradio）？ ![gihub_问题](https://private-user-images.githubusercontent.com/47628302/361127439-51810331-877c-4545-9ebd-deef817ac7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MzkxMjcsIm5iZiI6MTcyNDYzODgyNywicGF0aCI6Ii80NzYyODMwMi8zNjExMjc0MzktNTE4MTAzMzEtODc3Yy00NTQ1LTllYmQtZGVlZjgxN2FjN2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyMjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNGQwMGZkZjAyNzBiYmVjNDZkNjAzY2Q2NDQ1NzcyZWEwZjliMjBhN2M1MTE2NDgwNDMzNWI4NzFiYTczMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HreroV9Tv0GkoZa35z5AMs4jN5meHpaYju5iTUIvSa0)

Thank you for your attention to faceedit3d.  The edited photo should be named inverwrap_seed{seed:04d}_direction{angle:.2f}.png. Please check that the correct photo was generated.

In addition, after generating the landmark using [generate_3D_landmarks.py], you can edit the values ​​of target_3d_ldms.txt according to the order shown in the figure to implement the editing. 

The code for UI is being cleaned up and will be released after it is completed.

Thank you again for your attention to this work.

**Comment by cyh-sj** [comment]
> Hi, I tried running the command `python gen_inversion_wraped_images.py --outdir=out --network=ffhqrebalanced512-128.pkl --edit_shape True --directions=./editing_direction/fat.npy`, but the synthesis result doesn’t seem to show any changes. Is there anything wrong with my configuration? Also, how can I edit my own face? Are there any interactive applications available, similar to the original DragGAN implementation (e.g., using Imgui or Gradio)? ![gihub_issue](https://private-user-images.githubusercontent.com/47628302/361127439-51810331-877c-4545-9ebd-deef817ac7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Mzk2MzgsIm5iZiI6MTcyNDYzOTMzOCwicGF0aCI6Ii80NzYyODMwMi8zNjExMjc0MzktNTE4MTAzMzEtODc3Yy00NTQ1LTllYmQtZGVlZjgxN2FjN2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDFmYzNjODBjYmQzNzUyYTYyYzYzMjU1YmI3ZDBiNWYyMDFhMTBiOTA0NDc5M2QyYWM3ZGZjMWVjZDllMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.73VR0I86zDIr5SWVLxe0neyZBhtcbzZSH2BY0Un9yTw)

Thank you for your attention to faceedit3d. The edited photo should be named inverwrap_seed{seed:04d}_direction{angle:.2f}.png. Please check that the correct photo was generated.

In addition, after generating the landmark using [generate_3D_landmarks.py], you can edit the values ​​of target_3d_ldms.txt according to the order shown in the figure to implement the editing.

The code for UI is being cleaned up and will be released after it is completed.

Thank you again for your attention to this work.

**Comment by Dong142857** [comment]
Thanks for your kind guidance! I successfuly run this code. I notice current inference codes have some bugs and can not directly observe the editing result following the README.md. I pull a request with adding some codes and providing a brief launch script. Thank you for your excellence work!
